# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - nightly
  - 0.6
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes --inline=no -e 'Pkg.clone(pwd()); Pkg.build("TextWrap"); Pkg.test("TextWrap"; coverage=true)'
after_success:
  - julia -e 'Pkg.add("Documenter", v"0.6.0")'
  - julia -e 'cd(Pkg.dir("TextWrap")); include(joinpath("docs", "make.jl"))'
  - julia -e 'Pkg.add("Coverage", v"0.3")'
  - julia -e 'cd(Pkg.dir("TextWrap")); include(joinpath("docs", "coverage.jl"))'
