language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - nightly
notifications:
  email: false
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia --check-bounds=yes -e 'import Pkg; Pkg.clone(pwd()); Pkg.build("Reexport"); Pkg.test("Reexport"; coverage=true)'
after_success:
- julia -e 'import Pkg; cd(Pkg.dir("Reexport")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
