language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false

matrix:
  allow_failures:
  - julia: nightly

after_success:
  - julia -e 'using Pkg; Pkg.add("Documenter"); Pkg.add("Coverage")'
  - julia -e 'import BufferedStreams; cd(dirname(dirname(pathof(BufferedStreams)))); include(joinpath("docs", "make.jl"))'
  - julia -e 'using Coverage; import BufferedStreams; cd(dirname(dirname(pathof(BufferedStreams)))); Codecov.submit(process_folder())'
