language: julia
os:
    - linux
julia:
    - 0.6
    - 0.7
    - 1.0
    - nightly
notifications:
    email: false
matrix:
    allow_failures:
        - julia: nightly
sudo: false
after_success:
    - julia -e 'if VERSION >= v"0.7" using Pkg end; cd(Pkg.dir("YAML")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
