[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'Shougo/neco-syntax'
on_ft = 'vim'

[[plugins]]
repo = 'mechatroner/rainbow_csv'
on_ft = 'csv'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_source = '''
let g:vim_markdown_fenced_languages = ['c=c''c++=cpp', 'vim=vim', 'bash=sh', 'julia=jl']
'''

[[plugins]]
repo = 'suan/vim-instant-markdown'
on_ft ='markdown'
hook_source = '''
let g:instant_markdown_browser = "firefox --new-window"
set expandtab
'''

[[plugins]]
repo = 'zenlang/zen.vim'
on_ft = 'zen'

[[plugins]]
repo = 'sudar/vim-arduino-syntax'
on_ft = 'arduino'
